<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheel">

<xacro:property name="caster_wheel_radius" value="0.01"/>
<xacro:property name="caster_wheel_length" value="0.04"/>
<xacro:macro name="caster_wheel">

    <link name="caster_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="1.57 0 0"/>
            <geometry>
                <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}"/>
            </geometry>
            </visual>
        <collision>
            <origin xyz="0 0 0" rpy="1.57 0 0"/>
            <geometry>
                <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}"/>
            </geometry>
        </collision>
    </link>

    <link name="caster_fixed">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
            </visual>
        <collision>
            <origin xyz="0 0 0" rpy= "0 0 0"/>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
        </collision>
    </link>
    
    <link name="caster_top">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
            </visual>
        <collision>
            <origin xyz="0 0 0" rpy= "0 0 0"/>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
        </collision>
    </link>


<joint name="caster_wheel_joint" type="continuous">
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <parent link="caster_fixed"/>
    <child link="caster_wheel"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>
<joint name="caster_fixed_joint" type="fixed">
    <parent link="caster_top"/>
    <child link="caster_fixed"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>
<joint name="caster_top_joint" type="continuous">
    <axis xyz="0 0 1" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="caster_top"/>
    <origin xyz="0 0 ${(base_height/2) - base_distance_from_ground}" rpy="0 0 0"/>
</joint>

</xacro:macro>
</robot>