# Publish scans from best pose at a max of 10 Hz 
odom_model_type : diff
use_map_topic : true
gui_publish_rate : 10.0
laser_max_beams : 120
laser_max_range : 40.00
min_particles : 500
max_particles : 2000

kld_err : 0.01
kld_z : 0.99
odom_alpha1 : 0.01
odom_alpha2 : 0.01
odom_alpha3 : 0.01
odom_alpha4 : 0.01

laser_z_hit : 0.9
laser_z_short : 0.05
laser_z_max : 0.05
laser_z_rand : 0.5
laser_sigma_hit : 0.1
laser_lambda_short : 0.1
#laser_model_type : beam
laser_model_type : likelihood_field
laser_likelihood_max_dist : 4.0
update_min_d : 0.25
update_min_a : 0.2
odom_frame_id : odom
resample_interval : 1

# Increase tolerance because the computer can get quite busy 
transform_tolerance : 0.5
recovery_alpha_slow : 0.0
recovery_alpha_fast : 0.0
