odom_frame: odom
map_frame: map
base_frame : base_link


# Update frequencies
linearUpdate : 0.5
angularUpdate : 0.4
temporalUpdate : 2.0
resampleThreshold : 0.5
particles : 80


# Initial Map Size
delta : 0.02
xmin : -10
xmax : 10
ymin : -10
ymax : 10

#
#map_update_interval: 0.1 # Publish new map

maxUrange: 39.0 # Should be just less than sensor range
maxRange: 41.0 # Should be just greater than sensor range