local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05

  obstacle_range: 39.0
  raytrace_range: 41.0
  footprint: [[-1.5, 1.5], [1.5, 1.5], [1.5, -1.5], [-1.5, -1.5]]
  inflation_radius: 1.0

  obstacle_layer:
    observation_sources: laser_scan_sensor

  laser_scan_sensor: {
    sensor_frame: laser_scanner,
    data_type: LaserScan,
    topic: /myrobot/laser/scan,
    marking: true,
    clearing: true
  }

  plugins:
    - name: footprint
      type: "costmap_2d::FootprintLayer"
    - name: obstacles_layer
      type: "costmap_2d::ObstacleLayer"
    - name: inflater
      type: "costmap_2d::InflationLayer"