local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05

  obstacle_range: 6.0
  raytrace_range: 6.5
  #footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
  robot_radius: 0.75
  inflation_radius: 1.0

  observation_sources: laser_scan_sensor 

  laser_scan_sensor: {sensor_frame: laser_scanner, data_type: LaserScan, topic: myrobot/laser/scan, marking: true, clearing: true}