<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="camera_link">
    <xacro:property name="camera_width" value="0.08"/>
    <xacro:property name="camera_height" value="0.15"/>
    <xacro:property name="camera_length" value="0.08"/>
    <xacro:macro name="camera_link">

        <link name="camera_link">
            <visual>
                <geometry>
                    <box size="${camera_width} ${camera_length} ${camera_height}"/>
                </geometry>
            </visual>

            <collision>
                <geometry>
                    <box size="${camera_width} ${camera_height} ${camera_height}"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="1" w="${camera_length}" h="${camera_width}" d="${camera_height}"/>
        </link>

        <joint name="camera_joint" type="fixed">
            <parent link="base_link"/>
            <child link="camera_link"/>
            <origin rpy="0.0 0.0 0.0" xyz="0.45 0 ${base_height/2 + camera_height/2}"/>

        </joint>

        <!-- camera -->
        <gazebo reference="camera_link">
            <sensor type="camera" name="camera1">
                <update_rate>30.0</update_rate>
                <camera name="head">
                    <horizontal_fov>1.3962634</horizontal_fov>
                    <image>
                        <width>800</width>
                        <height>800</height>
                        <format>R8G8B8</format>
                    </image>
                    <clip>
                        <near>0.02</near>
                        <far>300</far>
                    </clip>
                    <noise>
                        <type>gaussian</type>
                        <!-- Noise is sampled independently per pixel on each frame.
                             That pixel's noise value is added to each of its color
                             channels, which at that point lie in the range [0,1]. -->
                        <mean>0.0</mean>
                        <stddev>0.007</stddev>
                    </noise>
                </camera>
                <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                    <alwaysOn>true</alwaysOn>
                    <updateRate>0.0</updateRate>
                    <cameraName>camera_link</cameraName>
                    <imageTopicName>image_raw</imageTopicName>
                    <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                    <frameName>camera_link</frameName>
                    <hackBaseline>0.07</hackBaseline>
                    <distortionK1>0.0</distortionK1>
                    <distortionK2>0.0</distortionK2>
                    <distortionK3>0.0</distortionK3>
                    <distortionT1>0.0</distortionT1>
                    <distortionT2>0.0</distortionT2>
                </plugin>
            </sensor>
        </gazebo>

    </xacro:macro>
</robot>