<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="camera_link">
    <xacro:property name="camera_width" value="0.02"/>
    <xacro:property name="camera_height" value="0.03"/>
    <xacro:property name="camera_length" value="0.02"/>
    <xacro:macro name="camera_link">

        <link name="camera_link">
            <visual>
                <geometry>
                    <box size="${camera_width} ${camera_length} ${camera_height}"/>
                </geometry>
            </visual>

            <collision>
                <geometry>
                    <box size="${camera_width} ${camera_height} ${camera_height}"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="1" w="${camera_length}" h="${camera_width}" d="${camera_height}"/>
        </link>

        <joint name="camera_joint" type="fixed">
            <parent link="base_link"/>
            <child link="camera_link"/>
            <origin rpy="0.0 0.0 0.0" xyz="${base_width/2 + camera_width/2} 0.0 ${camera_height + 0.01}"/>

        </joint>

    </xacro:macro>
</robot>