<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="camera_link">
    <xacro:property name="camera_width" value="0.02"/>
    <xacro:property name="camera_height" value="0.03"/>
    <xacro:property name="camera_length" value="0.02"/>
    <xacro:macro name="camera_link">

        <link name="camera_link">
            <visual>
                <geometry>
                    <box size="${camera_width} ${camera_length} ${camera_height}"/>
                </geometry>
            </visual>

            <collision>
                <geometry>
                    <box size="${camera_width} ${camera_height} ${camera_height}"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="1" w="${camera_length}" h="${camera_width}" d="${camera_height}"/>
        </link>

        <joint name="camera_joint" type="fixed">
            <parent link="base_link"/>
            <child link="camera_link"/>
            <origin rpy="0.0 0.0 0.0" xyz="${base_width/2 + camera_width/2} 0.0 ${camera_height + 0.01}"/>

        </joint>

        <!-- camera -->
        <gazebo reference="camera_link">
            <sensor type="depth" name="camera">
                <always_on>true</always_on>
                <update_rate>20.0</update_rate>
                <camera>
                    <horizontal_fov>1.3924</horizontal_fov>
                    <image>
                        <format>R8G8B8</format>
                        <width>1920</width>
                        <height>1080</height>
                    </image>
                    <clip>
                        <near>0.05</near>
                        <far>8.0</far>
                    </clip>
                </camera>
                <plugin name="kinect_camera_controller" filename="libgazebo_ros_openni_kinect.so">
                    <cameraName>camera</cameraName>
                    <alwaysOn>true</alwaysOn>
                    <updateRate>10</updateRate>
                    <imageTopicName>rgb/image_raw</imageTopicName>
                    <depthImageTopicName>depth/image_raw</depthImageTopicName>
                    <pointCloudTopicName>depth/points</pointCloudTopicName>
                    <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
                    <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
                    <frameName>camera_depth_optical_frame</frameName>
                    <baseline>0.1</baseline>
                    <distortion_k1>0.0</distortion_k1>
                    <distortion_k2>0.0</distortion_k2>
                    <distortion_k3>0.0</distortion_k3>
                    <distortion_t1>0.0</distortion_t1>
                    <distortion_t2>0.0</distortion_t2>
                    <pointCloudCutoff>0.4</pointCloudCutoff>
                </plugin>
            </sensor>
        </gazebo>

    </xacro:macro>
</robot>