<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheel">

 <xacro:property name="caster_wheel_radius" value="0.01"/>
 <xacro:property name="caster_wheel_length" value="0.04"/>
<xacro:macro name="caster_wheel">


    <link name="caster_wheel">
        <xacro:box_inertia m="1" w="0.1" h="0.1" d="0.1"/>
        <visual>
            <geometry>
                <sphere radius="0.1"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.1"/>
            </geometry>
        </collision>

    </link>

    <joint name="caster_joint" type="fixed">
        <origin xyz="-0.3 0 ${-(base_height/2)}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="caster_wheel"/>

        <calibration rising="0.0"/>
        <dynamics damping="0.0" friction="0.0"/>
    </joint>

    </xacro:macro>
</robot>