<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="laser_scanner">
<xacro:property name="laser_width" value="0.02"/>
<xacro:property name="laser_height" value="0.04"/>
<xacro:property name="laser_length" value="0.02"/>
<xacro:macro name="laser_scanner">

    <link name="laser_scanner">
        <visual>
            <geometry>
                <box size="${laser_width} ${laser_length} ${laser_height}"/>      
            </geometry>          
        </visual>    
        
        <collision>
            <geometry>
                <box size="${laser_width} ${laser_length} ${laser_height}"/>      
            </geometry>
        </collision>
        <xacro:box_inertia m="1" w="${laser_length}" h="${laser_width}" d="${laser_height}"/>
    </link>

    <joint name="laser_scanner_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_scanner"/>
        <origin rpy="0.0 0.0 0.0" xyz="${base_width/2 + laser_width/2} 0 0"/>
           
    </joint>

</xacro:macro>
</robot>