<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="myrobot">

    <xacro:property name="base_width" value="1"/>
    <xacro:property name="base_len" value="0.6"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="base_distance_from_ground" value="0.05"/>
    <xacro:include filename="$(find myrobot_description)/urdf/robot.gazebo.xml"/>

    <!--Color Properties-->

    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>
    <material name="orange">
        <color rgba="0.5 0.2 0.2 1"/>
    </material>
    <!--Interial macros-->
    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0" iyy="${m*(3*r*r+h*h)/12}" iyz="0" izz="${m*r*r/2}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="box_inertia" params="m w h d">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m / 12.0 * (d*d + h*h)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (w*w + h*h)}" iyz="0.0"
                     izz="${m / 12.0 * (w*w + d*d)}"/>
        </inertial>
    </xacro:macro>

    <link name="base_link">
        <xacro:box_inertia m="1" w="${base_len}" h="${base_width}" d="${base_height}"/>
        <visual>
            <geometry>
                <box size="${base_width} ${base_len} ${base_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_width} ${base_len} ${base_height}"/>
            </geometry>
        </collision>

    </link>

    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${0 - base_distance_from_ground - base_height/2}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="base_footprint"/>
    </joint>

    <xacro:include filename="$(find myrobot_description)/urdf/wheel.urdf.xacro"/>
    <xacro:wheel prefix="front_right" reflect_y="-1" reflect_x="1"/>
    <xacro:wheel prefix="front_left" reflect_y="1" reflect_x="1"/>
    <xacro:wheel prefix="back_right" reflect_y="-1" reflect_x="-1"/>
    <xacro:wheel prefix="back_left" reflect_y="1" reflect_x="-1"/>

    <xacro:include filename="$(find myrobot_description)/urdf/laser_scanner.urdf.xacro"/>
    <xacro:laser_scanner/>

    <xacro:include filename="$(find myrobot_description)/urdf/camera.urdf.xacro"/>
    <xacro:camera_link/>

    <link name="elevator">
    <inertial>
        <origin rpy="0 0 0" xyz="-2.7755575615628914e-15 -0.0022800822836666623 0.09050102854580892"/>
        <mass value="8.994467062407036"/>
        <inertia ixx="0.120393" ixy="-0.0" ixz="-0.0" iyy="0.325419" iyz="0.000697" izz="0.415842"/>
    </inertial>
    <visual>
        <origin rpy="0 0 0" xyz="-0.5 -0.305 -0.075"/>
        <geometry>
        <mesh filename="package://myrobot_description/meshes/elevator_1.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="red"/>
    </visual>
    <collision>
        <origin rpy="0 0 0" xyz="-0.5 -0.305 -0.075"/>
        <geometry>
        <mesh filename="package://myrobot_description/meshes/elevator_1.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>
    </link>

    <joint name="slider" type="prismatic">
    <origin rpy="0 0 0" xyz="0.0 0.0 -0.025"/>
    <parent link="base_link"/>
    <child link="elevator"/>
    <axis xyz="0.0 0.0 1.0"/>
    <limit effort="100" lower="0.0" upper="0.1" velocity="100"/>
    </joint>

	<!-- Transmission is important to link the joints and the controller (see rb1_control/config/rb1_control.yaml)-->
		<transmission name="elevator_platform_trans">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="slider">
				<!-- for the gazebo plugin -->
				<!--hardwareInterface>EffortJointInterface</hardwareInterface-->
				<!-- for ros control controller -->
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			</joint>            
			<actuator name="elevator_platform_joint_motor">    
				<hardwareInterface>EffortJointInterface</hardwareInterface>    
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
		</transmission>



</robot>
