<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="myrobot">

    <xacro:property name="base_width" value="1"/>
    <xacro:property name="base_len" value="1"/>
    <xacro:property name="base_height" value="0.5"/>
    <xacro:property name="base_distance_from_ground" value="0.1"/>
    <xacro:include filename="$(find myrobot_description)/urdf/robot.gazebo"/>

    <!--Color Properties-->

    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>
    <material name="orange">
        <color rgba="0.5 0.2 0.2 1"/>
    </material>
    <!--Interial macros-->
    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0" iyy="${m*(3*r*r+h*h)/12}" iyz="0" izz="${m*r*r/2}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="box_inertia" params="m w h d">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m / 12.0 * (d*d + h*h)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (w*w + h*h)}" iyz="0.0"
                     izz="${m / 12.0 * (w*w + d*d)}"/>
        </inertial>
    </xacro:macro>


    <link name="base_link">
        <xacro:box_inertia m="1" w="${base_len}" h="${base_width}" d="${base_height}"/>
        <visual>
            <geometry>
                <box size="${base_width} ${base_len} ${base_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_width} ${base_len} ${base_height}"/>
            </geometry>
        </collision>

    </link>

    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${0 - base_distance_from_ground - base_height/2}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="base_footprint"/>
    </joint>

    <xacro:include filename="$(find myrobot_description)/urdf/wheel.urdf.xacro"/>
    <xacro:wheel prefix="right" reflect="-1"/>
    <xacro:wheel prefix="left" reflect="1"/>

    <xacro:include filename="$(find myrobot_description)/urdf/caster_wheel.urdf.xacro"/>
    <xacro:caster_wheel/>

    <xacro:include filename="$(find myrobot_description)/urdf/laser_scanner.urdf.xacro"/>
    <xacro:laser_scanner/>

    <xacro:include filename="$(find myrobot_description)/urdf/camera.urdf.xacro"/>
    <xacro:camera_link/>

</robot>
