joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

elevator_controller:
  type:  effort_controllers/JointEffortController
  joint: slider
  pid: {p: 10.0, i: 0.1, d: 0.0}

mobile_base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'left_wheel_joint'
  right_wheel : 'right_wheel_joint'
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 1.0
  wheel_radius : 0.075

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5
  publish_cmd: true 
  # Base frame_id
  base_frame_id: base_link #default: base_link

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.0  # m/s
      min_velocity           : -0.5 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.1  # m/s^2
      min_acceleration       : -0.1 # m/s^2
      has_jerk_limits        : true
      max_jerk               : 2.0  # m/s^3
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.7  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.8  # rad/s^2
      has_jerk_limits        : true
      max_jerk               : 1.5  # rad/s^3
myrobot_elevator_controller:
  type        : "myrobot_elevator_controller/MyrobotElevatorController"
  joint:    
    elevator_joint:
      name: slider
  elevator_position_up: 10
  elevator_position_down: 0.0
  # delay time to perform the elevation
  elevation_action_time: 1.0
  # params for the pickup avoiding Gazebo physics
  gazebo:
    # if true, the carts will be raised avoiding contact
    disable_gazebo_physics_for_pickup: true
    pickup_service: "/elevator_fake_pickup_gazebo/simple_pick"
    place_service: "/elevator_fake_pickup_gazebo/simple_place"
    # distance in z to move the picked cart (disabled)
    # elevation_offset_z: 0.07  